config/routes.rb
Rails.application.routes.draw do
  resources :animes
  resources :series
  resources :movies
  resources :books
  resources :games
  devise_for :users
  
  root "pages#index"
end

app/models/anime.rb
class Anime < ApplicationRecord
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: [:show, :edit, :update, :destroy]

  # GET /animes
  # GET /animes.json
  def index
    @animes = Anime.all
  end

  # GET /animes/1
  # GET /animes/1.json
  def show
  end

  # GET /animes/new
  def new
    @anime = Anime.new
  end

  # GET /animes/1/edit
  def edit
  end

  # POST /animes
  # POST /animes.json
  def create
    @anime = Anime.new(anime_params)

    respond_to do |format|
      if @anime.save
        format.html { redirect_to @anime, notice: 'Anime was successfully created.' }
        format.json { render :show, status: :created, location: @anime }
      else
        format.html { render :new }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animes/1
  # PATCH/PUT /animes/1.json
  def update
    respond_to do |format|
      if @anime.update(anime_params)
        format.html { redirect_to @anime, notice: 'Anime was successfully updated.' }
        format.json { render :show, status: :ok, location: @anime }
      else
        format.html { render :edit }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animes/1
  # DELETE /animes/1.json
  def destroy
    @anime.destroy
    respond_to do |format|
      format.html { redirect_to animes_url, notice: 'Anime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime
      @anime = Anime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def anime_params
      params.require(:anime).permit(:name)
    end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/views/animes/_form.html.erb
<%= form_with(model: anime, local: true) do |form| %>
  <% if anime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

      <ul>
        <% anime.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animes/edit.html.erb
<h1>Editing Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Show', @anime %> |
<%= link_to 'Back', animes_path %>

app/views/animes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animes.each do |anime| %>
      <tr>
        <td><%= anime.name %></td>
        <td><%= link_to 'Show', anime %></td>
        <td><%= link_to 'Edit', edit_anime_path(anime) %></td>
        <td><%= link_to 'Destroy', anime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anime', new_anime_path %>

app/views/animes/new.html.erb
<h1>New Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Back', animes_path %>

app/views/animes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @anime.name %>
</p>

<%= link_to 'Edit', edit_anime_path(@anime) %> |
<%= link_to 'Back', animes_path %>