config/routes.rb
Rails.application.routes.draw do
  resources :animes
  resources :series
  resources :movies
  resources :books
  resources :games
  devise_for :users
  
  root "pages#index"
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Serie.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Serie.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Serie.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Serie was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Serie was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_url, notice: 'Serie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Serie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.require(:series).permit(:name)
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_with(model: series, local: true) do |form| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
        <% series.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_path %>

app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Series</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= series.name %></td>
        <td><%= link_to 'Show', series %></td>
        <td><%= link_to 'Edit', edit_series_path(series) %></td>
        <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', series_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @series.name %>
</p>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_path %>